# Generated by Django 3.2.4 on 2021-06-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_store_app', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lastLname',
            new_name='lastname',
        ),
    ]
