# Generated by Django 3.2.4 on 2021-06-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_store_app', '0004_auto_20210622_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
