# Generated by Django 3.2.4 on 2021-06-22 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_store_app', '0008_auto_20210622_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
