# Generated by Django 3.2.4 on 2021-06-22 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_store_app', '0009_rename_product_id_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
