# Generated by Django 3.2.4 on 2021-06-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_store_app', '0011_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amount',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
