# Generated by Django 3.2.4 on 2021-06-24 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_store_app', '0012_auto_20210623_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_store_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_store_app.product')),
            ],
        ),
    ]
