# Generated by Django 3.2.4 on 2021-06-24 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_store_app', '0014_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 6, 24, 4, 10, 34, 301748)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 6, 24, 4, 10, 53, 405316)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 6, 24, 4, 11, 25, 776803)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
